SpringMvc/src/main/java/com/unisyd_elec5619/springmvc/domain/EmojiFamilyImpl.java
package com.unisyd_elec5619.springmvc.domain;


import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.MapKeyEnumerated;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.springframework.util.Base64Utils;
import org.springframework.web.multipart.MultipartFile;

import com.unisyd_elec5619.springmvc.users.enums.EmojiLevelEnum;

@Entity
@Table(name="EmojiFamily")
public class EmojiFamilyImpl implements EmojiFamily {
	
	public EmojiFamilyImpl(){}
	
	public EmojiFamilyImpl(String emojiFamilyName, boolean defaultEmoji){
		this.name = emojiFamilyName;
		this.defaultEmoji = defaultEmoji;
	}
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	int id;
	@Override
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	private String name;
	public void setName(String name) {
		this.name = name;
	}

	boolean defaultEmoji;
	
	private transient MultipartFile fileLowMood;
	private transient MultipartFile fileMedMood;
	private transient MultipartFile fileHighMood;
	
	@Lob
	private byte[] emojiImageLow;
	public byte[] getEmojiImageLow() {
		return emojiImageLow;
	}

	public void setEmojiImageLow(byte[] emojiImageLow) {
		this.emojiImageLow = emojiImageLow;
	}

	@Lob
	private byte[] emojiImageMed;
	@Lob
	private byte[] emojiImageHigh;
	
	
	public MultipartFile getFileHighMood() {
		return fileHighMood;
	}

	public void setFileHighMood(MultipartFile file) {
		this.fileHighMood = file;
		try {
			emojiImageHigh =  file.getBytes();
		} catch (IOException e) {
			e.printStackTrace();
		}
	
	}

	public MultipartFile getFileMedMood() {
		return fileMedMood;
	}

	public void setFileMedMood(MultipartFile file) {
		this.fileMedMood = file;
		try {
			emojiImageMed =  file.getBytes();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public MultipartFile getFileLowMood() {
		return fileLowMood;
	}

	public void setFileLowMood(MultipartFile file) {
		this.fileLowMood = file;
			try {
				emojiImageLow =  file.getBytes();
			} catch (IOException e) {
				e.printStackTrace();
			}
	}

	public void setDefaultEmoji(boolean defaultEmoji) {
		this.defaultEmoji = defaultEmoji;
	}

	@Override
	public String getName() {
		return name;
	}

	@Override
	public boolean isDefaultEmoji() {
		return defaultEmoji;
	}

	@Override
	public String toString(){
		return "EmojiFamilyName: " + name + " Id: " + id + " Default: " + defaultEmoji + '\n'
				+ "multi part file size: " + fileLowMood.getSize();
	}
	
	@Override
	public Map<EmojiLevelEnum,byte[]> emojiImages(){
		Map<EmojiLevelEnum,byte[]> emojis = new HashMap<EmojiLevelEnum,byte[]>();
		emojis.put(EmojiLevelEnum.LOW, emojiImageLow);
		emojis.put(EmojiLevelEnum.MEDIUM, emojiImageMed);
		emojis.put(EmojiLevelEnum.HIGH, emojiImageHigh);
		return emojis;
	}
	
	
	public static String base64EncodedImage(byte[] emojiImage){
		// Code adapted from Stack Exchange http://stackoverflow.com/questions/26585804/show-image-on-jsp-with-spring-mvc-and-hibernate
		byte[] encodeBase64 = Base64Utils.encode(emojiImage);
		String base64Encoded = "";
		try {
		base64Encoded = new String(encodeBase64, "UTF-8");
		} catch (UnsupportedEncodingException e) {
		e.printStackTrace();
		}
		// End adapted code
		return base64Encoded;
		}	
	
	public String getBase64EncodedImageLow(){
		return base64EncodedImage(emojiImageLow);
	}
	
	public String getBase64EncodedImageMed(){
		return base64EncodedImage(emojiImageMed);
	}
	
	public String getBase64EncodedImageHigh(){
		return base64EncodedImage(emojiImageHigh);
	}
	
	
}

SpringMvc/src/main/java/com/unisyd_elec5619/springmvc/calendar/CalendarController.java
package com.unisyd_elec5619.springmvc.calendar;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.propertyeditors.CustomDateEditor;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.unisyd_elec5619.springmvc.domain.Project;
import com.unisyd_elec5619.springmvc.service.CalendarServiceImpl;
import com.unisyd_elec5619.springmvc.service.DatabaseProjectManager;
import com.unisyd_elec5619.springmvc.service.UserServiceImpl;
import com.unisyd_elec5619.springmvc.users.Users;
@Controller
public class CalendarController {
	
	@Resource(name="projectManager")
	private DatabaseProjectManager projectManager;
	
	private UserServiceImpl userService;
	private CalendarServiceImpl calendarService;
	
	@Autowired
	public void setUserServiceImpl(UserServiceImpl usersServiceImpl){
		this.userService = usersServiceImpl;
	}
	
	@Autowired
	public void setCalendarServiceImpl(CalendarServiceImpl calendarServiceImpl){
		this.calendarService = calendarServiceImpl; 
	}
	
	
	//	public String showCalendar(@Valid Users user, BindingResult result) {
	@RequestMapping("/calendar/{id}")
	public String showCalendar(Model model, @PathVariable("id") long id) {
		
		int maxYear = 2000;
		
		
		System.out.println("/calendar/" + id);
		
		Project currentProject = projectManager.getProjectById(id);
		
		System.out.println(currentProject.getName());
		
		Calendar cal = new Calendar();
		cal.setProjectID(id);
		
		model.addAttribute("projects", this.projectManager.getProjects());
		model.addAttribute("calendarobject", cal);
		model.addAttribute("currentproject", currentProject);
		
		User loggedUser = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		Users currentUser = userService.find(loggedUser.getUsername());
		
		
		model.addAttribute("username", loggedUser.getUsername());
		
		// THIS HERE NEEDS TO CHANGE
		/* XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
		 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
		 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		 */
		List<Calendar> dateList = calendarService.retrieveUserProjectCalendar(currentUser, id);
		List<DateLog> dateLogList = new ArrayList<DateLog>();
		
		
		
		for (Calendar c : dateList){
			// System.out.println("Datelist for : " + currentUser.getUsername() + " Date: " + c.getCurrentDate() + " Mood: " + c.getMood());
			
			String dateString = c.getCurrentDate().toString();
			int year = Integer.parseInt(dateString.substring(0,4));
			
			if ( year > maxYear){
				maxYear = year;
			}
		}
		
		for (Calendar c : dateList){
			// System.out.println("Datelist for : " + currentUser.getUsername() + " Date: " + c.getCurrentDate() + " Mood: " + c.getMood());
			
			String dateString = c.getCurrentDate().toString();
			int year = Integer.parseInt(dateString.substring(0,4));
			int month = Integer.parseInt(dateString.substring(5,7));
			int day = Integer.parseInt(dateString.substring(8,dateString.length()));
			int mood = c.getMood();
			
			if ( year == maxYear){
				dateLogList.add(new DateLog(year, month, day, mood));
			}
		}
		
		List<MonthLog> allMonths = new ArrayList<MonthLog>();
		allMonths.add(new MonthLog("January", 1, 31));
		allMonths.add(new MonthLog("February", 2, 28));
		allMonths.add(new MonthLog("March", 3, 31));
		allMonths.add(new MonthLog("April", 4, 30));
		allMonths.add(new MonthLog("May", 5, 31));
		allMonths.add(new MonthLog("June", 6, 30));
		allMonths.add(new MonthLog("July", 7, 31));
		allMonths.add(new MonthLog("August", 8, 31));
		allMonths.add(new MonthLog("September", 9, 30));
		allMonths.add(new MonthLog("October", 10, 31));
		allMonths.add(new MonthLog("November", 11, 30));
		allMonths.add(new MonthLog("December", 12, 31));
		
		model.addAttribute("maxYear", maxYear);
		model.addAttribute("dateMonths", allMonths);
		model.addAttribute("dateLog", dateLogList);
		
		for (DateLog d : dateLogList){
			System.out.println("dateLog | Year:" + d.getYear() + " month: " + d.getMonth() + " day: " + d.getDay() + " mood: " + d.getMood());
		}
		
		
		return "/calendar";
	}
	
	@RequestMapping(value = "/setemote", method=RequestMethod.POST)
	public String setEmote(@Valid Calendar calendarobject, BindingResult result, Model model){
		
		if (calendarobject.getCurrentDate() != null){
			if (result.hasErrors()){
				System.out.println(result);		
			}
			
			User loggedUser = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
			Users currentUser = userService.find(loggedUser.getUsername());
			
			calendarobject.setUserID(currentUser.getId());
			
			
			calendarService.save(calendarobject);
			
			return showCalendar(model, calendarobject.getProjectID());
		} else {

			model.addAttribute("error", true);
			return showCalendar(model, calendarobject.getProjectID());
		}
		

	}
	
	@InitBinder     
	public void initBinder(WebDataBinder binder){
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
	    binder.registerCustomEditor(Date.class, new CustomDateEditor(sdf, true));  
	}

}

SpringMvc/src/main/java/com/unisyd_elec5619/springmvc/dashboard/DashboardController.java
package com.unisyd_elec5619.springmvc.dashboard;

import java.util.List;
import java.util.Locale;

import javax.annotation.Resource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.unisyd_elec5619.springmvc.domain.Project;
import com.unisyd_elec5619.springmvc.service.CalendarServiceImpl;
import com.unisyd_elec5619.springmvc.service.DatabaseProjectManager;

/**
 * Handles requests for the application home page.
 */

@Controller
public class DashboardController {
	
	private static final Logger logger = LoggerFactory.getLogger(DashboardController.class);
	
	@Resource(name="projectManager")
	private DatabaseProjectManager projectManager;
	
	private CalendarServiceImpl calendarService;
	
	@Autowired
	public void setCalendarServiceImpl(CalendarServiceImpl calendarServiceImpl){
		this.calendarService = calendarServiceImpl; 
	}
	
	@RequestMapping(value = {"/","/dashboard", "/index.html", "/index", "/**/index", "/**/index.html"}, method = RequestMethod.GET)
	public String home(Locale locale, Model model) {

		
		User user = (User)SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		String name = user.getUsername();
		boolean enabled = user.isEnabled();
		
		model.addAttribute("username", name);
		model.addAttribute("enabled", enabled);
		model.addAttribute("projects", this.projectManager.getProjects());
		
		Project currentProject = null;
		
		for(Project p: this.projectManager.getProjects()){
			currentProject = p;
			break;
		}

		
		model.addAttribute("currentProject", currentProject);
		
		long pid = currentProject.getId();
		System.out.println("pid: " + pid);
		
		
		//FEED A PROPER PROJECT ID
		//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		model.addAttribute("totalIndex", calendarService.getTotalIndex(pid));
		model.addAttribute("overallMood", calendarService.getAvgMood(pid));
		
		logger.info("Welcome home! The client locale is {}.", locale);
		
		return "dashboard";
	}
	


	@RequestMapping(value = {"project/{id}"}, method = RequestMethod.GET)
	public String dynamicHome(Locale locale, Model model, @PathVariable("id") String id) {
		
		
		System.out.println("Path Var: " + id);
		
		User user = (User)SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		String name = user.getUsername();
		boolean enabled = user.isEnabled();
		
		model.addAttribute("username", name);
		model.addAttribute("enabled", enabled);
		model.addAttribute("projects", this.projectManager.getProjects());
		
		Project currentProject = null;
		
		for(Project p: this.projectManager.getProjects()){
			currentProject = p;
			break;
		}
		
		for (Project p : this.projectManager.getProjects()){
			if (p.getName().equals(id)){
				currentProject = p;
			}
		}
		
		
		model.addAttribute("currentProject", currentProject);
		
		long pid = currentProject.getId();
		System.out.println("pid: " + pid);
		
		
		//FEED A PROPER PROJECT ID
		//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		model.addAttribute("totalIndex", calendarService.getTotalIndex(pid));
		model.addAttribute("overallMood", calendarService.getAvgMood(pid));
		
		logger.info("Welcome home! The client locale is {}.", locale);
		
		return "dashboard";
	}

}

SpringMvc/src/main/java/com/unisyd_elec5619/springmvc/users/LoginController.java
package com.unisyd_elec5619.springmvc.users;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.unisyd_elec5619.springmvc.service.AuthorityServiceImpl;
import com.unisyd_elec5619.springmvc.service.UserServiceImpl;

@Controller
public class LoginController {

	private UserServiceImpl userServiceImpl;
	private AuthorityServiceImpl authorityServiceImpl;

	@Autowired
	public void setUserServiceImpl(UserServiceImpl usersServiceImpl) {
		this.userServiceImpl =  usersServiceImpl;
	}
	
	@Autowired
	public void setAuthorityServiceImpl(AuthorityServiceImpl authorityServiceImpl){
		this.authorityServiceImpl = authorityServiceImpl;
	}

	@RequestMapping("/login")
	public String showLogin() {
		
		// boolean au = SecurityContextHolder.getContext().getAuthentication().isAuthenticated();
		
		return "login";
	}

	@RequestMapping("/newaccount")
	public String showNewAccount(Model model) {

		model.addAttribute("user", new Users());
		return "newaccount";
	}

	@RequestMapping(value = "createaccount", method = RequestMethod.POST)
	public String createAccount(@Valid Users user, BindingResult result) {
		
		if (result.hasErrors()) {
			return "newaccount";
		}

		if (userServiceImpl.find(user.getUsername())  != null){
			return "/createaccount";
		}
		
		user.setAuthority("user");
		user.setEnabled(1);

		try {
			Authority au = new Authority(user.getUsername(), user.getAuthority());
			authorityServiceImpl.save(au);
			userServiceImpl.save(user);
			
		} catch (DuplicateKeyException e) {
			result.rejectValue("username", "DuplicateKey.user.username", "This username already exists.");
			return "/createaccount";
		}

		return "login";
	}

}

SpringMvc/src/main/webapp/WEB-INF/views/createaccount.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="sf" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="refresh"
	content="0; url=${pageContext.request.contextPath}/newaccount?error=true" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Creating account...</title>

</head>
<body>
	Wait one moment while you are redirected.
</body>
</html>

SpringMvc/src/main/webapp/WEB-INF/views/emojiTheme2.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ page session="false"%>

 <%-- Code adapted from http://www.journaldev.com/3531/spring-mvc-hibernate-mysql-integration-crud-example-tutorial --%>

<html>
<head>
<title>Emoji Themes</title>
<style type="text/css">
.tg {
	border-collapse: collapse;
	border-spacing: 0;
	border-color: #ccc;
}

.tg td {
	font-family: Arial, sans-serif;
	font-size: 14px;
	padding: 10px 5px;
	border-style: solid;
	border-width: 1px;
	overflow: hidden;
	word-break: normal;
	border-color: #ccc;
	color: #333;
	background-color: #fff;
}

.tg th {
	font-family: Arial, sans-serif;
	font-size: 14px;
	font-weight: normal;
	padding: 10px 5px;
	border-style: solid;
	border-width: 1px;
	overflow: hidden;
	word-break: normal;
	border-color: #ccc;
	color: #333;
	background-color: #f0f0f0;
}

.tg .tg-4eph {
	background-color: #f9f9f9
}
</style>
</head>
<body>
	<h1>Add an emoji theme</h1>

	<c:url var="addAction" value="/upload"></c:url>

	<form:form modelAttribute="emojiFamilyImpl" action="${addAction}" enctype="multipart/form-data">
		<table>
			<c:if test="${!empty emojiFamilyImpl.name}">
				<tr>
					<td><form:label path="id">
							<spring:message text="ID" />
						</form:label></td>
					<td><form:input path="id" readonly="true" size="8"
							disabled="true" /> <form:hidden path="id" /></td>
				</tr>
			</c:if>
			<tr>
				<td><form:label path="name">
						<spring:message text="Name" />
					</form:label></td>
				<td><form:input path="name" /></td>
			</tr>
			<tr>
				<td><form:label path="defaultEmoji">
						<spring:message text="Project default" />
					</form:label></td>
				<td><form:checkbox path="defaultEmoji" /></td>
			</tr>
			<tr>
				<td><form:label path="fileLowMood">
						<spring:message text="Low mood image (jpg file)" />
					</form:label></td>
				<td><form:input type="file" path="fileLowMood"/></td>
			</tr>
			<tr>
				<td><form:label path="fileMedMood">
						<spring:message text="Medium mood image (jpg file)" />
					</form:label></td>
				<td><form:input type="file" path="fileMedMood"/></td>
			</tr>
				<tr>
				<td><form:label path="fileHighMood">
						<spring:message text="High mood image (jpg file)" />
					</form:label></td>
				<td><form:input type="file" path="fileHighMood"/></td>
			</tr>
			<tr>
				<td colspan="2"><c:if test="${!empty emojiFamilyImpl.name}">
						<input type="submit" value="<spring:message text="Edit emoji theme"/>" />
					</c:if> <c:if test="${empty emojiFamilyImpl.name}">
						<input type="submit" value="<spring:message text="Add emoji theme"/>" />
					</c:if></td>
			</tr>
		</table>
	</form:form>

<br>
<h3>Emoji Family List</h3>
<c:if test="${!empty listThemes}">
	<table class="tg">
	<tr>
		<th width="80">Emoji ID</th>
		<th width="120">Emoji Name</th>
		<th width="120">Default</th>
		<th width="120">Low</th>
		<th width="120">Med</th>
		<th width="120">High</th>
		<th width="60">Edit</th>
		<th width="60">Delete</th>
	</tr>
	<c:forEach items="${listThemes}" var="theme">
		<tr>
			<td>${theme.id}</td>
			<td>${theme.name}</td>
			<td>${theme.defaultEmoji}</td>
			<td>
				<img src="data:image/jpeg;charset=utf-8;base64,${theme.base64EncodedImageLow}"/>
			</td>
			<td>
				<img src="data:image/jpeg;charset=utf-8;base64,${theme.base64EncodedImageMed}"/>
			</td>
			<td>
				<img src="data:image/jpeg;charset=utf-8;base64,${theme.base64EncodedImageHigh}"/>
			</td>
			<td><a href="<c:url value='/emojiThemeUpdate/${theme.id}' />" >Edit</a></td>
			<td><a href="<c:url value='/emojiThemeDelete/${theme.id}' />" >Delete</a></td>
		</tr>
	</c:forEach>
	</table>
</c:if>


</body>
</html>

SpringMvc/src/main/webapp/WEB-INF/views/error.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
Error 403. You do not have permission to go to this page. You may need to <a href= "${pageContext.request.contextPath}/login" >login</a> first.
</body>
</html>

SpringMvc/src/main/webapp/WEB-INF/views/include.jsp
<%@ page session="false"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

SpringMvc/src/main/webapp/WEB-INF/views/index.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page session="false" %>
<html>
<head>
	<title>Home</title>
</head>
<body>
<h1>
	Hello world!  
</h1>

<P>  The time on the server is ${serverTime}. </P>

<a href="/SpringMvc/hello.htm"> links to project list</a>
</body>
</html>

SpringMvc/src/main/webapp/WEB-INF/views/userResult.jsp
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="mvc" %>
<%@ page session="false" %>
<html>
<head>
	<title>User Form Result</title>
</head>
<body>

<body>
<h2>User Registration Result</h2>
<table>
    <tr>
        <td>Name</td>
        <td>${u.nameFirst}</td>
    </tr>
    <tr>
        <td>Last name</td>
        <td>${u.nameLast}</td>
    </tr>
    <tr>
        <td>Password</td>
        <td>${u.password}</td>
    </tr>
    <tr>
        <td>Detail</td>
        <td>${u.detail}</td>
    </tr>
    <tr>
        <td>Birth Date</td>
        <td>${u.birthDate}</td>
    </tr>
    <tr>
        <td>Gender</td>
        <td>${u.gender}</td>
    </tr>
    <tr>
        <td>Country</td>
        <td>${u.country}</td>
    </tr>
    <tr>
        <td>Non-Smoking</td>
        <td>${u.nonSmoking}</td>
    </tr>
</table>
</body>
</html>